### ISSUE TITLE
vite host and port option

### ISSUE THREAD

**Issue by u007** [TomokiMiyauci/vite-plugin-ssr-ssg#137]
i tried to set host and port inside vite.config.ts, but it didnt work with this plugin when i run npm run dev.
when i run npm run serve, i got it running on port 5000 (which is not working as well).

```
const port = Number(process.env.PORT || '3330');
export default defineConfig({
  server: {
    https: true,
    host: process.env.HOST || '127.0.0.1',
    port,
    fs: {
      strict: true
    }
  },

**Comment by TomokiMiyauci** [comment]
@u007 Thank you for your interest in this project.

This project has not been well tested and has many bugs. 
Currently, my plan is not to improve this project.
It should be used as an example for SSR and SSG implementations.

Please use [vite-plugin-ssr](https://github.com/brillout/vite-plugin-ssr) instead.

**Comment by u007** [comment]
Hi @TomokiMiyauci okay thank you for letting me know
